### ISSUE TITLE
Update the readme file

### ISSUE THREAD

**Issue by avishka-nable** [avishka-nable/Dbt-Demo#4]
https://n-abledev.atlassian.net/browse/DA-2569?atlOrigin=eyJpIjoiODAxNjg5ZTA4ZDdmNDdiNjhkMGFhMjJkYmIzMjFiOTkiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #5 from avishka-nable/ah/feature/004/update_readme_file
